name: ey-nlp
channels:
  - anaconda-fusion
  - defaults
dependencies:
  - alabaster=0.7.12=py37_0
  - appnope=0.1.0=py37_0
  - asn1crypto=1.2.0=py37_0
  - astroid=2.3.2=py37_0
  - attrs=19.3.0=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py37_0
  - beautifulsoup4=4.8.1=py37_0
  - blas=1.0=mkl
  - bleach=3.1.0=py37_0
  - boto=2.49.0=py37_0
  - boto3=1.9.234=py_0
  - botocore=1.12.234=py_0
  - bz2file=0.98=py37_1
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py37_0
  - cffi=1.13.0=py37hb5b8e2f_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py37_0
  - cloudpickle=1.2.2=py_0
  - cryptography=2.8=py37ha12b0ac_0
  - cycler=0.10.0=py37_0
  - cytoolz=0.9.0.1=py37h1de35cc_1
  - dbus=1.13.12=h90a0687_0
  - decorator=4.4.0=py37_1
  - defusedxml=0.6.0=py_0
  - dill=0.2.9=py37_0
  - docutils=0.15.2=py37_0
  - entrypoints=0.3=py37_0
  - expat=2.2.6=h0a44026_0
  - flask=1.1.1=py_0
  - freetype=2.9.1=hb4e5f40_0
  - gensim=3.8.0=py37h6440ff4_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - icu=58.2=h4b95b61_1
  - idna=2.8=py37_0
  - imagesize=1.1.0=py37_0
  - importlib_metadata=0.23=py37_0
  - intel-openmp=2019.4=233
  - ipykernel=5.1.2=py37h39e3cac_0
  - ipython=7.8.0=py37h39e3cac_0
  - ipython_genutils=0.2.0=py37_0
  - isort=4.3.21=py37_0
  - itsdangerous=1.1.0=py37_0
  - jedi=0.15.1=py37_0
  - jinja2=2.10.3=py_0
  - jmespath=0.9.4=py_0
  - joblib=0.13.2=py37_0
  - jpeg=9b=he5867d9_2
  - jsonschema=3.1.1=py37_0
  - jupyter_client=5.3.4=py37_0
  - jupyter_core=4.6.0=py37_0
  - keyring=18.0.0=py37_0
  - kiwisolver=1.1.0=py37h0a44026_0
  - lazy-object-proxy=1.4.2=py37h1de35cc_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.37=ha441bb4_0
  - libsodium=1.0.16=h3efe00b_0
  - llvm-openmp=4.0.1=hcfea43d_1
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.1=py37h54f8f79_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.14=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - more-itertools=7.2.0=py37_0
  - msgpack-numpy=0.4.4.3=py_0
  - msgpack-python=0.5.6=py37h04f5b5a_1
  - murmurhash=0.28.0=py37h0a44026_0
  - nbconvert=5.6.0=py37_1
  - nbformat=4.4.0=py37_0
  - ncurses=6.1=h0a44026_1
  - nltk=3.4.5=py37_0
  - numpy=1.17.2=py37h99e6662_0
  - numpy-base=1.17.2=py37h6575580_0
  - numpydoc=0.9.1=py_0
  - openssl=1.1.1d=h1de35cc_3
  - packaging=19.2=py_0
  - pandas=0.25.2=py37h0a44026_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.5.1=py_0
  - pcre=8.43=h0a44026_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_0
  - pip=19.3.1=py37_0
  - plac=0.9.6=py37_0
  - prompt_toolkit=2.0.10=py_0
  - psutil=5.6.3=py37h1de35cc_0
  - ptyprocess=0.6.0=py37_0
  - pycodestyle=2.5.0=py37_0
  - pycparser=2.19=py37_0
  - pyflakes=2.1.1=py37_0
  - pygments=2.4.2=py_0
  - pylint=2.4.3=py37_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h655552a_2
  - pyrsistent=0.15.4=py37h1de35cc_0
  - pysocks=1.7.1=py37_0
  - python=3.7.4=h359304d_1
  - python-dateutil=2.8.0=py37_0
  - python.app=2=py37_9
  - pytz=2019.3=py_0
  - pyzmq=18.1.0=py37h0a44026_0
  - qt=5.9.7=h468cd18_1
  - qtawesome=0.6.0=py_0
  - qtconsole=4.5.5=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h1de35cc_5
  - regex=2018.07.11=py37h1de35cc_0
  - requests=2.22.0=py37_0
  - rope=0.14.0=py_0
  - s3transfer=0.2.1=py37_0
  - scikit-learn=0.21.3=py37h27c97d8_0
  - scipy=1.3.1=py37h1410ff5_0
  - setuptools=41.4.0=py37_0
  - sip=4.19.8=py37h0a44026_0
  - six=1.12.0=py37_0
  - smart_open=1.8.4=py_0
  - snowballstemmer=2.0.0=py_0
  - soupsieve=1.9.3=py37_0
  - sphinx=2.2.0=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - spyder=3.3.6=py37_0
  - spyder-kernels=0.5.2=py37_0
  - sqlite=3.30.1=ha441bb4_0
  - termcolor=1.1.0=py37_1
  - testpath=0.4.2=py37_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h1de35cc_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.3=py37_0
  - ujson=1.35=py37h1de35cc_0
  - urllib3=1.24.2=py37_0
  - wcwidth=0.1.7=py37_0
  - webencodings=0.5.1=py37_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - wrapt=1.10.11=py37h1de35cc_2
  - wurlitzer=1.0.3=py37_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.3.1=h0a44026_3
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - blis==0.4.1
    - cymem==2.0.2
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.2.0/en_core_web_md-2.2.0.tar.gz
    - preshed==3.0.2
    - spacy==2.2.1
    - srsly==0.2.0
    - thinc==7.1.1
    - wasabi==0.3.0
prefix: /Users/roberthatem/anaconda3/envs/ey-nlp

